### ISSUE TITLE
The riemann client opened 98 threads and all of them blocked at sun.nio.ch.EPollArrayWrapper.epollWait

### ISSUE THREAD

**Issue by Root-Fang** [riemann/riemann-java-client#86]
Hi developer:

I use riemann-java-client 0.4.3 in my program. And I found there are 98 threads blocked at sun.nio.ch.EPollArrayWrapper.epollWait. The flowing the call stack generated by jcmd Thread.print.

"New I/O worker #19172423" #19963249 prio=5 os_prio=0 tid=0x00007f5e70806800 nid=0x11a1a runnable [0x00007f60354d3000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000001de60b0c8> (a sun.nio.ch.Util$3)
	- locked <0x00000001de60b0b8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000001de60b070> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:410)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:207)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mcorbin** [comment]
Hi,

What JVM/Linux version do you use ?

**Comment by Root-Fang** [comment]
java : openjdk version "1.8.0_161"
Linux: Linux version 3.10.0-514.el7.x86_64
@mcorbin
